TARGET = HelloWorld

all:HelloWorld

HelloWorld: HelloWorld.c
	gcc -o HelloWorld HelloWorld.c

TARGET = Seq_Fault

all:Seq_Fault

Seq_Fault: seq_fault.c
	gcc -o Seq_Fault seq_fault.c

TARGET = SortedList

all:SortedList

SortedList: sorted_list.c sorted_list.h
	gcc -o SortedList sorted_list.c -I .

